### ISSUE TITLE
Düzeldi mi?

### ISSUE THREAD

**Issue by MuratCN** [FatmaOk/exer#2]
Başka bir dosya eklemeyi dene. Örneğin kendi klonladığın Repoya birkaç dosya ekleyip onları sırasıyla

* Stage-area'ya ekle(git add .)
* Commit ile kayıt altına al (git commit -m "mesaj")
* Gönder (git push)

Fork: Kendi repona kopyalama ve orada istediğin düzeltmeyi yapmak
Issue: Hata veya soru isteklerim
Pull requests: Benim yaptıklarımı düzeltme isteği

**Comment by MuratCN** [comment]
#2

**Comment by FatmaOk** [comment]
Teşekkür ederim düzeldi 👍

**Comment by MuratCN** [comment]
Rica ederim
